// swift-tools-version: 5.9
import PackageDescription

// GENERATED by scripts/fix-ios-spm-paths.mjs after `cap sync` — do not hand-edit.
// Local package identity = last path component (required by modern SwiftPM / Xcode 26).
let package = Package(
    name: "CapApp-SPM",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "CapApp-SPM",
            targets: ["CapApp-SPM"])
    ],
    dependencies: [
        .package(url: "https://github.com/ionic-team/capacitor-swift-pm.git", exact: "8.4.1"),
        .package(path: "../../../plugins/solara-widget"), // identity: solara-widget
        .package(path: "../../../node_modules/@capacitor/app"), // identity: app
        .package(path: "../../../node_modules/@capacitor/browser"), // identity: browser
        .package(path: "../../../node_modules/@capacitor/geolocation"), // identity: geolocation
        .package(path: "../../../node_modules/@capacitor/haptics"), // identity: haptics
        .package(path: "../../../node_modules/@capacitor/keyboard"), // identity: keyboard
        .package(path: "../../../node_modules/@capacitor/local-notifications"), // identity: local-notifications
        .package(path: "../../../node_modules/@capacitor/push-notifications"), // identity: push-notifications
        .package(path: "../../../node_modules/@capacitor/splash-screen"), // identity: splash-screen
        .package(path: "../../../node_modules/@capacitor/status-bar"), // identity: status-bar
    ],
    targets: [
        .target(
            name: "CapApp-SPM",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm"),
                .product(name: "SolaraWidget", package: "solara-widget"),
                .product(name: "CapacitorApp", package: "app"),
                .product(name: "CapacitorBrowser", package: "browser"),
                .product(name: "CapacitorGeolocation", package: "geolocation"),
                .product(name: "CapacitorHaptics", package: "haptics"),
                .product(name: "CapacitorKeyboard", package: "keyboard"),
                .product(name: "CapacitorLocalNotifications", package: "local-notifications"),
                .product(name: "CapacitorPushNotifications", package: "push-notifications"),
                .product(name: "CapacitorSplashScreen", package: "splash-screen"),
                .product(name: "CapacitorStatusBar", package: "status-bar"),
            ]
        )
    ]
)
